### ISSUE TITLE
Building for new MySQL

### ISSUE THREAD

**Issue by matt-horwood-mayden** [borb/c6buildenv#1]
Hi Borb,

WE have tried your RPM and it looks for MySQL 5.5, I would guess that a yum update would be good in your vagrent file no?

**Comment by matt-horwood-mayden** [comment]
Also adding yum-builddep will help get a vanilla vm ready for building php

**Comment by borb** [comment]
Hello Mattholomew,

Today's update should build against CentOS 6's mysql-libs package, which is both provided by the base system & Oracle's mysql-community repository for CentOS/RHEL 6.
